### ISSUE TITLE
Title types

### ISSUE THREAD

**Issue by lucianacioca** [lombardpress/lombardpress-schema#109]
The following situation is a bit uncertain in the titleStmt:
 when we have a diplomatic transcription from an incunabulum for which we give 2 titles, a long and a short one:
<title>In quatuor libros Sententiarum</title>
Where and how should we add the longer title on the front page: F. Guilelmi de Rubicone venerabilis admodum patris et theologi facile doctissimi provincie Aragonice quondam Ministri Disputatorum in quatuor libros Magistri Sententiarum. Tomus prior super primum et secundum diligenter ab Iodoco Badio Ascensio impressus et indice sequenti illustratus.

**Comment by lucianacioca** [comment]
Should we use the TEI specifications
<title type="desc">F. Guilelmi de Rubicone venerabilis admodum patris et theologi facile doctissimi provincie Aragonice ..</title>
<title tpe="short">In quator libros Sententiarum</title>

**Comment by stenskjaer** [comment]
This is for the `titleStmt` of the `teiHeader` right? My first thought is that those fields are meta-text, which means that it does not need to represent transcribed material. The title, in my opinion, should be what you as editor consider (or decide) the title to be. There might be disadvantages in having several `title` elements in the header (unless there are clear policies for disambiguating in cases of conflict). 

If you want to reflect the title as it is indicated in the frontmatter of a particular witness to a text, you can do that in your diplomatic transcription of that particular witness. There are some guidelines for that here: http://www.tei-c.org/release/doc/tei-p5-doc/en/html/DS.html#DSTITL. I believe that it should not conflict with our LBP guidelines, although we have the more specific element `front/div@type='starts-on'` where we indicate starting folio of a text (http://lombardpress.org/schema/docs/critical/#front). 

These are my first thoughts, and I'm open to corrections.

**Comment by jeffreycwitt** [comment]
@lucianacioca, I believe each file you are working on corresponds to a particular question within the larger commentary. Thus the title for this file should correspond to the specific question, not the entire work.

The title you list above is a title for the entire work. 

We maintain different files to organize all the metadata about a particular work (or "expression"), it's various "manifestations" (witnesses), and the various parts contained within that "expression". 

Thus, while this is a desirable piece of metadata, it is a piece data we would preserve in our "expression-description" files (currently and unfortunately called "projectfiles").

The following article will be a little confusing for you, but it will introduce you to the main data model we us to describe scholastic texts: http://lombardpress.org/2016/06/12/scta-modeling-proposal/ It's a modification of data model called FRBR.

@stenskjaer In light of this question: we might thinking opening ticket in the projectfiles repo that notes we would like the ability to record both normalized and diplomatic titles for each manifestation of given expression.
