### ISSUE TITLE
Pagebreaks and column breaks

### ISSUE THREAD

**Issue by stenskjaer** [lombardpress/lombardpress-schema#11]
Here are some notes for a suggestion on how to handle page, folio and column breaks by a combination of `<pb>` and `<cb>`. We have different scenarios, since we can have layouts either with or without columns.

@jeffreycwitt: I know this isn't quite what we talked about yesterday, so I will look forward to your thoughts and counter arguments.

## Some overall possibilities
It would be possible to encode full page/folio references in `<cb>`s without any use of `<pb>`, but `<cb>` does not (in my opinion) semantically represent the phenomenon of a page break.
This gives us two possibilities:

1. Accept that a folio without columns could be considered a “single column” layout and use `<cb>` as the only milestone indicator. This means we don't recommend using `<pb>` at all.
2. Combine the `<pb>` and `<cb>` to differentiate the two phenomena. This means making `<pb>` a **MUST**, and `<cb>` would then be **MAY**, depending on the layout. This can be handled in two ways. Either as (a.) a rich encoding of the location, including page/folio number and side as well as the column reference, or (b.) a more thin encoding, only referring to the column.

### Pros and cons

On solution 1:
- Pro 1: A more one-tag-does-it-all approach. 
- Con 1: The unsemantic markup of “single column” layouts. The same information, the page/folio number and side, would be encoded multiple times. A processor would have to take that into account in parsing the `<cb>`s when looking for a page/folio number or side.

On solution 2:
- Pro 2: Distinction between different levels of the material hierarchy. In this way a processing that only considers page/folio breaks does not need to perform any parsing of the `@n`-string of `<cb>` but just get the `@n` of the `<pb>`. 
- Con 2: Unnecessary multiplication of tags. 

On the possibilities of solution 2:
- With 2a: If there are `<cb>`s, only parsing that will be able to yield the correct and unambiguous location. Which would be functionally equivalent to option 1 (in the case of a column layout).
- With 2b: The exact location would be a combination of a `<pb>` and a `<cb>`.

In favour of 2b: In the case of 2a, the same information will be encoded in both the `<pb>` and `<cb>` (namely the page/folio number and side). 2b would remove that redundancy.

I think the preference in these questions is partly a question of temperament. Do you prefer a flat and rich encoded or a nested representation where the combined exact location is spread over several tags or possible with an encoding redundancy where the same information is represented in several locations. That might partly be a matter of personal inclination.

I know that I personally prefer option 2a. As I conceive of it, the semantic value of the tags sufficiently represent the material hierarchy, and you avoid redundant encoding.

### Element attributes
If solution 1, this would be the attributes of `<cb>`. If solution 2, this would be the attributes of `<pb>` and `<cb>`.
- `@n` **MUST**: The value of this depends on whether it is a `<pb>` or `<cb>` and the choice of either full or sparse references.
- `@ed` **MUST**: Indicate the witness which contains this milestone.
- `@corresp` **MAY** (or **SHOULD**?): Point to the short canvas id of the folio in question.
- `@type` **MAY**: Indicate the type of numbering as either paginated or foliated. If none is given, `type="folio"` is assumed. In the case of 2b, this would only be an attribute of `<pb>`.

This would provide sufficient information for a processor to unambiguously identify a location.

The format of `@n` depends on the value of `@type`. 
- `type="folio"`: [folio number]-[side]-[column]
- `type="page"`: [page number]-[column]

The folio or page number includes additions such as ‘a’ or ‘bis’ in the case of duplicate numbers. The side would typically be either ‘r’ or ‘v’, but I guess the actual content of that could depend on the choice of the editor (?). How about column refernces? Typically it would be ‘a’, ‘b’ etc. but need not necessarily be. I guess this formatting could be value agnostic. We could suggest foliation with ‘r’ and ‘v’ and column references as ‘a’, ‘b’ etc. as **RECOMMENDED**.

### Processing the information
The advantage of solution 1 is the simple layout. You only have to get and parse the value of one attribute.

I (right now) tend to favour solution 2b, the combined use of `<pb>` and `<cb>` and sparse referencing in the `@n`-attributes.

So how should a processor respond when running into a `<pb>` or `<cb>`?

Time for an example:
Take this XML:
```xml
<pb ed="#W" n="15-r" /><cb ed="#W" n="a" />
Quo usque  tandem abutere, Catilina, patientia 
<cb ed="#W" n="b" />
nostra? Quam diu etiam furor iste tuus nos eludet?
```

When parsing page breaks, we could get the values like this:
```xslt
<xsl:template match="/p">
  folio: <xsl:value-of select="substring-before(pb/@n, '-')"/>
  folio side: <xsl:value-of select="substring-after(pb/@n, '-')"/>
  column: <xsl:value-of select="pb/following::cb[1]/@n"/>
  location: <xsl:value-of select="translate(pb/@n, '-', '')"/><xsl:value-of select="pb/following::cb[1]/@n"/>
</xsl:template>
```

This would return:
```
  folio: 15
  folio side: r
  column: a
  location: 15ra
```
If you have a single column layout (= no `<cb>`s), that makes no difference. It just doesn't return any value for the column location.

How about the case of a column change?
Take the following XSLT:
```xslt
<xsl:template match="cb">
  column: <xsl:value-of select="@n"/>
  folio: <xsl:value-of select="translate(preceding::pb/@n, '-', '')"/>
  location: <xsl:value-of select="translate(preceding::pb/@n, '-', '')"/><xsl:value-of select="@n"/>
</xsl:template>
```

This would return:
```
  column: a
  folio: 15r
  location: 15ra

  column: b
  folio: 15r
  location: 15rb
```

As we can see, although processing the locations of column breaks includes backtracking, the identification of the `<pb>` is pretty trivial, as I see it. So I don't consider that a big problem.

### `<cb>`
- `@ed` **MUST** indicate the source text in which the column break occurs.
- `@n` **MUST** indicate the column, e.g. a
- `@select` **MAY** have an point to the short canvas id of the folio in question the short canvas id should be combined in processing with the @xml:base attribute of the <witness> element declared in the sourceDesc/listWitness/witness

### `<pb>`
- `@ed` **MUST** indicate the source text in which the page break occurs.
- `@n` **MUST** indicate the page or folio number (determined by `@type`). In the case of `type="folio"`, the side of the folio is delimited by a `-`. 
- `@corresp` **MAY** (or **SHOULD**?): Point to the short canvas id of the folio in question.
- `@type` **MAY**: Indicate the type of numbering as either paginated or foliated. If none is given, `type="folio"` is assumed.

Folio break example: `<pb ed="#W" n="15-b" />`
Page break example: `<pb ed="#W" n="15" type="page" />`

**Comment by jeffreycwitt** [comment]
We've adopted Michael's proposal.
