### ISSUE TITLE
Is indication of starting folio a requirement?

### ISSUE THREAD

**Issue by stenskjaer** [lombardpress/lombardpress-schema#114]
I'm not sure the presence of the `front/div[@xml:id='starts-on']` is really a **MUST**.

In some cases it is not necessary. Some critical editions do not necessarily indicate folio numbering (if for instance there are very many witnesses or what ever) -- though you might argue whether that's a bad practice.  The obvious example for me though is translations, where it does not make a lot of sense to have the folio references to me.

**Comment by jeffreycwitt** [comment]
Won't there be a historical material witness to every text, whether a critical or diplomatic transcriptions.

I kind of still like seeing folio breaks inserted into a translation. The break will in many cases be approximate, but it helps us find the primary source underlying the translation.

Nevertheless, with respect to translations, I'm wondering if we need a third schema category for "translations".

**Comment by stenskjaer** [comment]
You might of course be right: There will always be the material foundation of a text. The decision of including it in a representation could be made at the processor level.

Good question about the translation schema. I'll make an issue for discussing that, see #115.
