### ISSUE TITLE
lb-elements at end of line rather than start

### ISSUE THREAD

**Issue by stenskjaer** [lombardpress/lombardpress-schema#14]
Cf. #3: I wonder whether it might increase readability to put the line break tag at the end of each line in the diplomatic transcriptions rather than at the beginning? I think this would correspond more closely with the practise determined in #3 of having the `<lb>` at the end and pull the last part of a split word up to the preceding line. This would also avoid the situation where one graphic line in the transcription contains two `<lb>`'s, which seems unsemantic to me.

I believe to have seen this discussion a couple of places, but don't remember the arguments for having the line break at the beginning of the line. Maybe you do, and maybe they are good?

**Comment by jeffreycwitt** [comment]
After much debate, I think we decided milestones would indicate the beginning of a page, column, or line. The TEI guidelines seemed to suggest this, and Jeff bullied everyone into get his own way.
