### ISSUE TITLE
divided quotations

### ISSUE THREAD

**Issue by jeffreycwitt** [lombardpress/lombardpress-schema#15]
This image is an example of a use case where we might need to manage "divided quotes". This issue is similar to how might need to handle divided apparatus entries.

<img width="1438" alt="divided-quote" src="https://cloud.githubusercontent.com/assets/1146685/16171469/9750541e-353d-11e6-9d19-fd63ef8d58f6.png">

**Comment by nivaca** [comment]
Still, the second part of the quote isn't wrapped in the first `<cit>`. Isn't that a problem?

**Comment by jeffreycwitt** [comment]
I think it is ok.

In this case, since we know that the second `<quote>` is connected to the first, we know that the `<bibl>` for the first quotation also applies in the second. Further, we only need to add a `<cit>` wrapper when want to associate a `<bibl>` with a sibling `<quote>`, so no `<cit>` element would be necessary in the second case.

**Comment by stenskjaer** [comment]
I think this looks like a great solution!

**Comment by jeffreycwitt** [comment]
Adopted.
