### ISSUE TITLE
Transpositions in diplomatic and critical editions

### ISSUE THREAD

**Issue by stenskjaer** [lombardpress/lombardpress-schema#19]
How do we mark up transpositions in the critical apparatus?

In the context of the diplomatic transcriptions, I propose simply to follow the TEI guidelines on the use of metamarks in transposition of material (see http://www.tei-c.org/release/doc/tei-p5-doc/en/html/PH.html#transpo). 

Example:

``` xml
Advertendum est<metamark function="transposition" target="#tr_secundum1" place="above" />
<seg xml:id="tr_secundum1">secundum</seg> Philosophum 
<metamark function="transposition" target="#tr_ulterius1" place="above"/>
<seg xml:id="tr_ulterius1">ulterius</seg>
<listTranspose>
  <transpose>
    <ptr target="#tr_ulterius1"/>
    <ptr target="#tr_secundum1"/>
  </transpose>
</listTranspose>
supra: dupliciter aliquod est
```

But I wonder how that is reflected in a critical edition.

Maybe something like this:

``` xml
Advertendum est
<app>
  <lem>ulterius secundum Philosophum</lem>
  <rdg wit="#L">
    <metamark function="transposition" target="#tr_secundum1" place="above" />
    <seg xml:id="tr_secundum1">secundum</seg> Philosophum 
    <metamark function="transposition" target="#tr_ulterius1" place="above"/>
    <seg xml:id="tr_ulterius1">ulterius</seg>
    <listTranspose>
      <transpose>
        <ptr target="#tr_ulterius1"/>
        <ptr target="#tr_secundum1"/>
      </transpose>
    </listTranspose>
  </rdg>
  <rdg wit="#P">secundum Philosophus ulterius</lem>
</app>
supra: dupliciter aliquod est
```

I believe that this would capture quite accurately what happens in the witness, but on the other hand the handling of it by a processor might be complex. An alternative would be to presented a more interpreted version in the critical context:

``` xml
Advertendum est
<app>
  <lem>ulterius secundum Philosophum</lem>
  <rdg wit="#L">
    <metamark function="transposition" target="#tr_ulterius1" place="above"/>
    <seg xml:id="tr_ulterius1">ulterius</seg>
    <metamark function="transposition" target="#tr_secundum1" place="above" />
    <seg xml:id="tr_secundum1">secundum</seg> Philosophum
  </rdg>
  <rdg wit="#P">secundum Philosophus ulterius</lem>
</app>
supra: dupliciter aliquod est
```

Or maybe the more simple and less flexible version:

``` xml
Advertendum est
<app>
  <lem>ulterius secundum Philosophum</lem>
  <rdg wit="#L">
    ulterius secundum Philosophum<note><mentioned>ulterius</mentioned> ante <mentioned>secundum</mentioned> pos.</note>
  </rdg>
  <rdg wit="#P">secundum Philosophus ulterius</lem>
</app>
supra: dupliciter aliquod est
```

I wouldn't be too much in favour of this, because it really is no different from the old fashioned apparatus where the presentation of the material gets mixed with the structure. Here it wouldn't be possible for a processor to understand what is going on, and only to a very limited extent determine how it would be presented.

Edit: Change `<q>` to `<mentioned>` after thinking a bit about that...

**Comment by jeffreycwitt** [comment]
Oofta, this is getting complicated. 

Could this be a special instance of corrReplace that we could call corrTransposition. 

(As a general aside: I think its going to be useful to think of variant types in terms of general and specific  patterns. Thus the encoding of all sub types of a more general type should follow a similar logical pattern. In this case, we have a generic case of "correction", then we have a case of a "correction replacement" and I wonder if it is possible to see a "correction transposition" as an even more specific kind "correction replacement".)

Here's a possible proposal.

    <app>
         <lem>ulterius secundum Philosophum</lem>
        <rdg wit="#L" type="corrTransposition">
            <subst>
                <del rend="transposition">secundum Philosophum ulterius</del>
                <add>ulterius secundum Philosophum</add>
            </subst>
       </rdg>
        <rdg wit="#P">secundum Philosophus ulterius</lem>
     </app>

My feeling (right now) is that it's best to keep the apparatus entry as simple as possible, and push any desire for rigorous accuracy about the precise rendering of a correction into the diplomatic transcriptions.

The above encoding would be sufficient to produce the following rendering:

    ulterius secundum Philosophum] _transp. ex_ secundum Philosophum ulterius L 

If the entire correction in the diplomatic transcriptions were wrapped in a `<seg xml:id="correctionid" type="correction">` (as discussed in: https://github.com/lombardpress/lombardpress-schema/issues/1) we could reference the correction using the `@corresp` attribute on the `<rdg>` element.

**Comment by jeffreycwitt** [comment]
@stenskjaer didn't we resolve this, at least in the apparatus guidelines with the "correction-transposition" category. 

If you agree, please go ahead and close.

**Comment by jeffreycwitt** [comment]
FYI for the diplomatic transcription of a transposition (see image below), 
I'm mostly following the TEI example as @stenskjaer suggested. 

![image](https://user-images.githubusercontent.com/1146685/48638535-e9b72a80-e99e-11e8-9236-ecbbf94ecbfc.png)

But I've also wrapped the entire correction in <seg type="correction"> 

```xml
          <seg type="correction">
            <seg xml:id="word1">non</seg>
              <metamark function="transposition" target="#word1" place="above">"</metamark>
            <seg xml:id="word2">sit</seg>
              <metamark function="transposition" target="#word2" place="above">"</metamark>
            <listTranspose>
              <transpose>
                <ptr target="#word2"/>
                <ptr target="#word1"/>
              </transpose>
            </listTranspose>
          </seg>
```
This example can be found in scta-texts/hby3dh/hby3dh-d1e65/cod-rtyu7r_hby3dh-d1e65.xml
