### ISSUE TITLE
paraphrased quotations or statements that we want to provide bibliography entry for

### ISSUE THREAD

**Issue by jeffreycwitt** [lombardpress/lombardpress-schema#20]
I was working on this text today. (Notice footnote number 1 in the image)

![img_20160622_084839](https://cloud.githubusercontent.com/assets/1146685/16267198/731c131e-3856-11e6-82d0-b3b840e4416e.jpg)

Here the editors want to attribute this position or claim to Aristotle even though it is not a direct quote. 

The phase in Latin part of the text is: "res est vel non est oratio vera vel falsa dicitur"

I think we should continue to use our general pattern of `<cit>` wrapping the text and along with an associated `<bibl>`. But the question is how to wrap the text itself. 

It does not seem accurate to call this a reference. It is also not a direct quote. I first thought about use `<seg>` because `<seg>` is completely generic and just identifies a "segment" of text.

                        <cit>
      				<seg>res est vel non est oratio vera 
      				vel falsa dicitur</seg>
      				<bibl>Aristotle, Categ. 5, 4b8-10: 12, 14b21-3</bibl>
      			</cit>

But TEI does not seem allow `<cit>` to contain `<seg>` as a child (which seems crazy to me). See: [http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-cit.html](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-cit.html)

So the best thing I could come up with is creating a "paraphrase" type for `<quote>` like this:

                        <cit>
      				<quote type="paraphrase">res est vel non est oratio vera 
      				vel falsa dicitur</quote>
      				<bibl>Aristotle, Categ. 5, 4b8-10: 12, 14b21-3</bibl>
      			</cit>

Generally, I expect that `<quote type="paraphrase">` is any assertion that we generally want to attribute to another author, but we probably not put in quotation marks.

(Even if this example is not the best fit for `<quote type="paraphrase">` I definitely think we need the general ability to distinguish quote types in this way.)

Edit, Michael: Changed an apostrophe to backtick in `<quote type="paraphrase">` (otherwise it isn't rendered)

**Comment by stenskjaer** [comment]
I agree completely. 

It surprises me that there is no tag for that in the TEI already. A `<paraphrase>`-tag would seem natural to have.

**Comment by stenskjaer** [comment]
I just ran into a closely related problem.

Take this phrase:
> Ad secundum dicendum quod motus dicitur dupliciter: Uno modo est actus inperfecti, sicut diffinitur in tercio Phisicorum, alio modo est actus perfecti sicut intelligere et cognoscere dicunter motus

How would you encode that? It is neither a quote nor a paraphrase. My first intuition would be to use `<ref>` like so:
```xml
Ad secundum dicendum quod motus dicitur dupliciter: Uno modo est actus inperfecti,
<cit>
  <ref>sicut diffinitur in tercio Phisicorum,</seg>
  <bibl>Aristotle, Phys. III 2 201b31--33.</bibl>
</cit>
alio modo est actus perfecti sicut intelligere et cognoscere dicunter motus
```
Do you see any problem in that?

**Comment by jeffreycwitt** [comment]
Yes, that is exactly how I would encode this.

**Comment by jeffreycwitt** [comment]
I think we're agreed that `<quote>` is equivalent to `<quote type="direct">` which allows us to have a `<quote type="paraphrase">` as well.
