### ISSUE TITLE
Notes in apparatus entries

### ISSUE THREAD

**Issue by stenskjaer** [lombardpress/lombardpress-schema#21]
Spurred by the previous issue (#19), I am not sure if we have any policy of handling notes in the apparatus.

If I would like to leave a note relevant for the interpretation of a reading in the apparatus, how should that be encoded?

I suggest just putting a note inside the `<rdg>`-tag, like so:

``` xml
Advertendum est
<app>
  <rdg wit="#L">
    ulterius secundum Philosophum <note>This presents us with 
    a superior reading in an inferior witness</note>
  </rdg>
  <rdg wit="#P">secundum Philosophus ulterius</lem>
</app>
supra: dupliciter aliquod est
```

The example note might not be too good, but the idea is to present notes that comment on the reading. It might also represent the structure of the reading, like I illustrated with the same passage in #19, but I am not sure that is a good idea (unless there might be some edge case where it cannot be represented by the markup, and in that case).

Related: #13.

**Comment by jeffreycwitt** [comment]
Notes should definitely be allowed. I've done it like this:

![image](https://cloud.githubusercontent.com/assets/1146685/16268299/dab02ea2-385b-11e6-873a-3e627c5e4da4.png)

The only difference is that I think you are suggesting embedding the `<note>` within each reading. For the time being, and for the sake of simplicity, I think we should require `<note> to be a sibling of all `<rdg>` elements and normally expect that there would be just one `<note>` per apparatus entry. 

(Though it remains possible that we could have multiple `<notes>` and they could be related to a specific `<rdg>` through an `@corresp` attribute.)

**Comment by stenskjaer** [comment]
Yes, I knew that you had used that already, I just couldn't find an example. But that is great.

I have actually used both at the same time:
See this passage:
![skaermbillede 2016-06-22 kl 15 47 00](https://cloud.githubusercontent.com/assets/4047523/16268939/a7599d6a-3890-11e6-9a03-254bc2311a17.png)

I have encoded roughly like so:
```xml
Probatio consequentiae:
<app>
  <lem>quia</lem>
  <rdg wit="#L">
    <add place="above">quia</add> quando
    <note><mentioned>quia quando</mentioned> 
      with the <mentioned>quia</mentioned> written above the 
      <mentioned>quando</mentioned>
    </note>
  </rdg>
  <note>To let <q>quia</q> replace <q>quando</q> seems the most sensible 
  interpretation of the suprascript quia.</note>
</app>
non est dubium <supplied>quin</supplied> anima
```
But I think that was also caused by the fact that I didn't know to encode what I saw, namely that the *quia* was written above the *quando* (and that I actually took that to mean that it should replace it). But here the note to the `<rdg>` explain how I read it, while the note to the `<app>` explain why I prefer that reading.
Does that make sense? Any suggestions for improving it are appreciated.

**Comment by jeffreycwitt** [comment]
I think our decision was allow both notes and witDetail. But both of these should be siblings rather than children of the rdg. witDetail can point to a rdg with an attribute pointer. 

Feel free to reopen if I'm incorrect.

**Comment by stenskjaer** [comment]
I am now writing a suggestion for the conjectures and I wonder whether you might also want to make it possible to have a `note` on the `lem` and `rdg` element?

I think that conceptually, making a note on a general apparatus entry and on a reading or lemma are different things.
For example:
``` xml
Utrum fides semper
<app>
  <lem type="conjecture-supplied">
    <supplied>sit</supplied>
    <note>Considering the context, this must be missing... </note>
  </lem>
  <rdg type="absent" wit="#P #V #L"/>
  <rdg type="conjecture-supplied" src="#Witt">
    <supplied>erit</supplied>
    <note>Dr. Witt finds the future a better reading</note>
  </rdg>
  <note>Editors are not in agreement about the required emendation... </note>
</app>
acquisita
```
These different notes serve different purposes determined by their immediate context. It would be more cumbersome to collect all the notes into on element. On the other hand, it might make some of the processing simpler. But as I see it, this makes it easier to make more specific notes (without having to make references and ids and what not).

@jeffreycwitt, I know you are opposed to elements that are not parallel (like `<lem>sed<note>note content</note></lem>`), but isn't that always what you have when you add `note` elements in a `<p>` or similar?

**Comment by jeffreycwitt** [comment]
This has been resolved with PR https://github.com/lombardpress/lombardpress-schema/pull/92
