### ISSUE TITLE
Referring to terms in comments and notes

### ISSUE THREAD

**Issue by stenskjaer** [lombardpress/lombardpress-schema#22]
When creating notes, either in body text or the apparatus referring to terms in the text, I believe we should use `<mentioned>`, rather than `<q>`, since it is not a quote, but a reference to a term.

This is related to #21 and #19 (on notes) and #10 where that tag has been suggested in a slightly different context (I don't know if it fits better for this case). I have just argued for the use of it in #16, and I don't know if these different uses interfere, but it doesn't seem so to me. 

Example:

``` xml
Advertendum est
<app>
  <rdg wit="#L">
    ulterius secundum Philosophum <note>The transposition of 
    <mentioned>ulterius</mentioned> gives us a superior reading in an inferior witness</note>
  </rdg>
  <rdg wit="#P">secundum Philosophum ulterius</lem>
</app>
supra: dupliciter aliquod est
```

**Comment by stenskjaer** [comment]
Come to think of it, I wonder if maybe `<w>` would be better? What I want to represent is material supposition, to convey “I am now referring to the term X”. I can't really figure out if that's a type of quote. 

The `<w>` is described like so in the TEI documentation
> <w> (word) represents a grammatical (not necessarily orthographic) word. 
http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-w.html

So it is of a more specific character. There is a comparison with `<mentioned>` in the Guidelines, and it is stated that `<mentioned>` can contain a `<w>`, but not the other way around. (http://www.tei-c.org/release/doc/tei-p5-doc/en/html/AI.html#AILCW)

**Comment by jeffreycwitt** [comment]
I think we've resolved this with in our description of `witDetail` 

https://github.com/lombardpress/lombardpress-schema/blob/ca5b01e/docs/1.0/critical/index.md#witdetail

We've bacially adopted the use of `mention` but we prefer `witDetail` over `note` for note related to specific `rdgs`

It should look like the following
```
Advertendum est
<app>
  <rdg wit="#L">
    ulterius secundum Philosophum</rdg 
    <witDetail wit="#L>
        The transposition of 
        <mentioned>ulterius</mentioned> 
        us a superior reading in an inferior witness
    </witDetail>
  </rdg>
  <rdg wit="#P">secundum Philosophum ulterius</lem>
</app>
supra: dupliciter aliquod est
```
