### ISSUE TITLE
Handling of abbreviations and expansions

### ISSUE THREAD

**Issue by stenskjaer** [lombardpress/lombardpress-schema#23]
We need to think about whether we want to handle expansions of abbreviations in a particular way.
We have not really made much use of this (I think) in our transcriptions yet, but I find it a pretty important feature in some contexts.

This is to me a difficult question, and I am not even sure if we want to implement any specific recommendations on this matter. There are already a range of different possibilities within the TEI standard and good reflections on the choices involved in the process in the handbook (http://www.tei-c.org/release/doc/tei-p5-doc/en/html/PH.html#PHAB), so maybe we should just leave it at that. 
Alternatively, we could make some more specific recommendations, but I am not sure that (1) we would have any changes specific to the situation of medieval philosophical/theological material and (2) that we would even be able to make general recommendations that would apply in any such case. 

After all, it is, as we see in the TEI handbook, mostly a question of editorial policy.

Do you have any view on whether we could make any meaningful distinctions or recommendations of relevance to the context of Lombard Press?

**Comment by jeffreycwitt** [comment]
See 1.0.0 diplomatic guidelines, abbreviations section.
