### ISSUE TITLE
Reading type to indicate correction by deletion

### ISSUE THREAD

**Issue by stenskjaer** [lombardpress/lombardpress-schema#24]
This reading type indicates that the text of one witness has been corrected, either by the original scribe or a later hand. 

An example of a deletion of a whole word, it could look like this:
```xml
quod dicit 
<app>
  <lem />
  <rdg wit="#S" type="correction_deletion">
    <del>cum</del>
  </rdg>
  <rdg wit="#L">cum</rdg>
</app>
Aristoteles
```
Required attribute: `@type="correction_deletion"` (or whatever name we agree on)
Facultative attributes: `@rend`, indicating the rendition of the deletion. Suggested values are: strikethrough, expunctuated, blackout, erasure. 

I think that when the scribe deletes a part of a word, it should be considered a substitution rather than a deletion, since it has a direct effect on the whole word that they are a part of.

Pending a decision in #17, my don't know yet what the name of the type will be.

Edit: Add notes on the two attributes.

**Comment by jeffreycwitt** [comment]
We adopted a version of this: `<rdg type="correction-deletion">`
