### ISSUE TITLE
Camelcase or underscores

### ISSUE THREAD

**Issue by stenskjaer** [lombardpress/lombardpress-schema#25]
I have been toiling a bit over proposals for reading types, but I find it difficult to propose a terminology before we agree on a scheme for variable naming. It is difficult for me to make proposals that I feel impede readability, but if we agree on in, I will of course comply.
I know that the current draft for documentation of 1.0.0 uses camelcase, but I just want to raise the issue because I personally find camelcased variable names less readable than underscored names. 

Studies [1] show that the training in one style negatively impacts the proficiency in the other. This means that my preference for underscored names might mean that I find camelcased names significantly less readable that you, if you are used to camelcased variables.
(Side note: I am used to PascalCased names in the context of class names, but that is a different case, I think)

Any thoughts on the age old dispute?

[1] referenced here: http://programmers.stackexchange.com/a/46326

**Comment by jeffreycwitt** [comment]
I'm very happy with moving to underscore notation. 

I used to camelCase from javascript and and underscore notation in Ruby. I'm not very discipline in this regard, so I'll be glad to be part of a team that enforces correct style. 

So let's start moving things toward underscore notations generally (at least for LombardPress. I've been using camelCase in the RDF database pretty consistently and I think it best to just keep it that way for now).

**Comment by jeffreycwitt** [comment]
One other note. Isn't it pretty common to use "dashes" rather than "underscores" for XML and HTML attributes. Consider typical class names used in css and javascript development.

**Comment by stenskjaer** [comment]
You are right that dashes might be a more typical use in the markup language domain. I can't figure out right now what the practice is in TEI, but we might also consider emulating that.

I definitely think you should keep the RDF database camelcased for now. No reason to start changing that just because of this change in property naming.

**Comment by jeffreycwitt** [comment]
I think we've settled on "dashes" throughout.
