### ISSUE TITLE
Apparatus reading manual override

### ISSUE THREAD

**Issue by jeffreycwitt** [lombardpress/lombardpress-schema#27]
As I look at more and more apparatus entries, the variety of entries appears overwhelming. It seems unlikely that we are going to be able to enumerate enough apparatus `@types` to satisfy every editor's desire, at least as we try to document version 1.0.0 of the lbp-schema.

I wonder if we could include an `@type` called `manual` which would let an editor "hard code" how he or she would like the apparatus entry to appear in printed form. 

I am imagining something like this: 

    <app>
       <lem>fides</lem>
       <rdg wit="#V" type="manual">fides] fides <hi rend="italic">corr. ex interl.</hi> fide V</rdg>
   </app>

Obviously, this is not be considered best practice and should not be encouraged. But let's say we publish  lbp-schema 1.0.0 it includes 15 different apparatus types. 

It's likely than editor may find a case that doesn't fit the 15 we enumerated. In such a case, we don't want an editor rejecting the idea of "semantic" encoding entirely because he or she believes that our schema does not allow them the flexibility to encode an idiosyncratic variant in their apparatus. 

Plus, this would provide us with a useful mechanism for further developing our list of apparatus types for version 2.0.0. In preparation for version 2.0.0 we could run a search for all `<apps>` with `@type="manual"` and then discuss if we can create a generic type for this use case.

**Comment by stenskjaer** [comment]
Agree 100%. That's a good idea. But I'm unsure whether it's a good idea to put the intended wording of the note as part of the content of the reading itself. That seems to me to confuse two different levels of markup (representation and interpretation).

But I think you might use the `<desc>` element on the reading, like so:

```xml
<app>
  <lem>fides</lem>
  <rdg wit="#V" type="manual">
    fides
    <desc><hi rend="italic">corr. ex interl.</hi> fide V</desc>
  </rdg>
</app>
```
But personally I don't think the `<hi>` element belongs, as it conflates structure and presentation. 
I would maybe suggest:

```xml
<app>
  <lem>fides</lem>
  <rdg wit="#V" type="manual">
    fides
    <desc>corr. ex interl. <mentioned>fide</mentioned> V</desc>
  </rdg>
</app>
```

The definition of `<desc>` in the Handbook sounds like this:
> `<desc>` (description) contains a brief description of the object documented by its parent element, including its intended usage, purpose, or application where this is appropriate.

**Comment by jeffreycwitt** [comment]
Interesting. But in your last example, we  would have no way to know what part to italicize (e.g. corr. ex interl.) and which part not to italicize (e.g. "V"). 

I'm not very uncomfortable using `<hi>` and presentation logic in this case precisely because the manual override is basically saying, "screw it, I don't know how to describe this semantically, I'm just going to tell you how I want it to look." This is why `@type=manual` should be avoided and only used as a temporary stop gap measure.

**Comment by stenskjaer** [comment]
I understand the point about the manual description of the presentation as well as the content of the note.
I overlooked that “V” was not marked as italic, and that made me realize that of course that should be encoded as `<wit>` (http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-wit.html).
The editor does not necessarily know (and should not have too much power over) the typography of the text if it gets used in a different context. 
Who says, for instance, that you want to italicize the witness sigil, why not put it in bold for instance?

What I do think should be possible for the editor, is to input a custom critical note, if she does not find the suggested list of types adequate. But she should not really decide how to interpret the different semantic categories graphically in the encoding itself. That belongs to a different layer of processing, as I see it.

But maybe I'm too optimistic about the possibilities of semantic encoding, and you might be right that there might be plenty of cases where an editor cannot see how to avoid mixing graphical and semantic markup. But for the specific case of lemma and witness I think it should be encouraged that at least those are categorized semantically.

An improved representation would be:
```xml
<app>
  <lem>fides</lem>
  <rdg wit="#V" type="manual">
    fides
    <desc>corr. ex interl. <mentioned>fide</mentioned> <wit>V</wit></desc>
  </rdg>
</app>
```

If you wanted the typographical representation that you indicated, you could still do that. 
For instence in in LaTeX:
```latex
\emph{corr. ex interl. \emph{fide} V}
```
Or in HTML
```html
<em class="italic">corr. ex interl. <span class="lemma">fide</span> V</em>
```
with the CSS:
```css
em.italic {
  font-style: italic;
}
span.lemma {
  font-style: normal;
}
```
This way you also maintain the possibility of creating specific representations of witness sigils (or just italics, of course).
