### ISSUE TITLE
Reading type to indicate transposition of words

### ISSUE THREAD

**Issue by stenskjaer** [lombardpress/lombardpress-schema#28]
This is inspired by @jeffreycwitt's recommendation in #19: 

``` xml
<app>
    <lem>ulterius secundum Philosophum</lem>
    <rdg wit="#L" type="correction-transposition">
        <subst>
            <del rend="transposition">secundum Philosophum ulterius</del>
            <add>ulterius secundum Philosophum</add>
        </subst>
   </rdg>
    <rdg wit="#P">secundum Philosophus ulterius</lem>
 </app>
```

@jeffreycwitt adds a `@rend="transposition"` to the `<del>` element, but actually I am uncertain whether that's necessary. As long as the type of the reading is already defined. Any thoughts?

How about longer transpositions? What do we do in a situation like this:

> I did not think we should have done that before they would do that

to

> I did think we should have done that before they would not do that

This might be a bit contrived, but having such a long passage in the note might seem a bit impractical. Often you might want to explain it in the note (if it was written manually), such as:

> not _ante_ do _transp. V_

But how would you encode that semantically? Is it possible to do in a general way that is easy to handle with the processor?

**Comment by jeffreycwitt** [comment]
We didn't explicitly make a `correction-transposition`. Should we? If we do I think this is clearly and sub-species of `correction-substitution`. Nevertheless, if an editor wants the rendered version to read `not ante do transp. V` `correction-substitution`. 

Let me know if you guys want to add this. 

For my part, I don't mind adding it as long as it is understood as a subtype of `correction-substitution` and that this is made clear in the guidelines.

I'll keep this open for now.

**Comment by stenskjaer** [comment]
Well, I would vote for a separate reading type since that would make it easier to create a different rendering during processing.

**Comment by jeffreycwitt** [comment]
a correction-transposition section has been added. See: https://github.com/lombardpress/lombardpress-schema/blob/ca5b01e/docs/1.0/critical/index.md#correction-transposition
