### ISSUE TITLE
Punctuation after elements

### ISSUE THREAD

**Issue by stenskjaer** [lombardpress/lombardpress-schema#31]
This might not strictly speaking be a Lombard Press question, but maybe you have a suggestion.
How do you handle punctuation after elements?
Take this example:

``` xml
Et partes vegetativae sunt nutritivum et
generativum, augmentativum. Sensitivae vero auditiva,
olfactiva et
<app>
  <lem>huiusmodi</lem>
  <rdg wit="#L">huius</rdg>
</app>.
Anime proprietates autem vegetative sunt nutrire,
augere, generare. 
```

The sentence ends after the apparatus entry, and I want to put a full stop. But I don't think it is right to put the full stop after the `</app>` element, so I put it on the following line (“. Anime ...”), but then I get problems with whitespace after processing the text.
How do you handle this?

**Comment by jeffreycwitt** [comment]
I actually think you'll have white space problems either way. When terms are moved to the next line Saxon usually asserts a space between the last word and the period.

White space is tricky. In my LaTeX conversion, I've actually built a "white space removal" step using the Unix `sed` command based on predictable patterns. 

I can show you this next we meet. It actually seems to work pretty well.

For my part, I have begin to prefer: 
   
```XML
    <app>
        <lem>huiusmodi</lem>
        <rdg wit="#L">huius</rdg>  
    </app>.
    Anime

**Comment by nivaca** [comment]
Oh, all right. However, I think there should be a nice LaTeX (or perhaps 
LuaLaTeX) solution for this issue.

Cheers.

Nick
