### ISSUE TITLE
Reading type to indicate the presence of word/phrase

### ISSUE THREAD

**Issue by stenskjaer** [lombardpress/lombardpress-schema#32]
This is terminologically difficult, as it is taken to represent the opposite situation of when a witness does not have a part of the text that other witnesses or the established text has. 

It explains the fact that one or more witnesses contain a word or expression that is not present in all versions of the text.

We have talked about calling it an *addition*.
Another suggestion could simply be *present*. It signifies that the content of the element is present in the indicated witness(es). It does *not* mean that it is caused by a conscious act of the scribe, which seems to be implied by *addition*.

Say we have a text with three witnesses, *P, V* and *L*:
```xml
sed anima est incorporealis
<app>
  <lem />
  <rdg wit="#P #L" />
  <rdg wit="#V" type="present">igitur et cetera</rdg>
</app>
```
In an old fashioned edition this might (for instance) be reflected in an apparatus entry like so:
> igitur et cetera *post* incorporealis *add. V*

And this is probably the reason for the confusion, for no *addition* has taken place. One witness simply has some content that is not present in the other witnesses or the edited text.
So a better way of representing it might be:
> igitur et cetera *post* incorporealis *habet V*

I therefore suggest the reading type *present* to represent that situation.

Note: This is my take on this. Please come with your suggestions for a better way of expressing this situation.

Edit: Some changes corresponding to the newly added #33, and the substitution of *addition* with *present* in the example.

**Comment by jeffreycwitt** [comment]
we adopted  `correction-present` in the guidelines.
