### ISSUE TITLE
Reading type that indicates the absence of a word/phrase

### ISSUE THREAD

**Issue by stenskjaer** [lombardpress/lombardpress-schema#33]
When we have a witness that does not have a part of the text that other witnesses or the established text has, I suggest to call that type *absent*.

It explains the fact that one or more witnesses *does not* contain a word or expression that is present in the established text or other witnesses.

The current term we use term, *omission*, is unclear as it implies that the reason for the alternative reading is a conscious act of the scribe. But we usually cannot know that. We can only establish the fact that the word/phrase is missing from that version of the text.

Say we have a text with three witnesses, *P, V* and *L*:
```xml
sed anima est incorporealis,
<app>
  <lem>igitur et cetera</lem>
  <rdg wit="#P #L">igitur et cetera</rdg>
  <rdg wit="#V" type="absent" />
</app>
```

This suggestion is closely related to #32 and completely parallel. It represents the exact opposite situation.

**Comment by jeffreycwitt** [comment]
We adopted this in the guidelines as `variation-absent`
