### ISSUE TITLE
Reading type: correction-addition

### ISSUE THREAD

**Issue by stenskjaer** [lombardpress/lombardpress-schema#34]
This indicates that a scribe (either the original or a later) has realized that a word/phrase is missing in the version written on the page and subsequently added it.

```xml
in nomine Patri et
<app>
  <lem>Filii et</lem>
  <rdg wit="#L"><add place="above-line">Filii et</add></rdg>
</app>
Spiritus Sancti.
```

The reading must contain the elemen `<add>` which must specify a value of the attribute `@place`.
Currently, the suggested possible values of the attribute are:
- in-line
- above-line
- below-line
- margin-top
- margin-right
- margin-bottom
- margin-left
- margin-center (in the case of more than two columns, the center margin is numbered from the left, e.g. margin-center-1 for the margin between column one and two from the left)

I suggest that the `<add>` may specify the `@rend` attribute to indicate if the addition is marked by a sign in the text. It could for instance be `rend="marked"` or with a reference to a description of a character of some sort (any ideas for how to do that the best way?).
Any thoughts on that? Maybe values to use?

**Comment by jeffreycwitt** [comment]
This was more or less adopted, except we didn't decide on margin-center-1, 2 etc. We can just use margin-center for the moment. If use cases emerge we can put this on the list for schema 1.1.
