### ISSUE TITLE
Dealing with scribal misspellings (and other minor mistakes) in the critical apparatus

### ISSUE THREAD

**Issue by jeffreycwitt** [lombardpress/lombardpress-schema#37]
I think its pretty clear that when a scribe makes an obvious mistake, we want to encode this as follows in the diplomatic transcription.

    <choice><sic>disproositionem</sic><corr>dispositionem</corr></choice>

But I'm wondering how we want to do this in the critical apparatus:

We can obviously do something like this.

    <app>
        <lem>dispositionem</lem>
	<rdg wit="#B">disproositionem</rdg>
    </app>

But this also provides us with no mechanism to distinguish between substantial variants versus simple spelling mistakes. In other words, in the above entry, I don't see the manuscript as actually containing a substantial variant. It's not like he was really copying a different word. He just spelled the word wrong (or accidentally added a loop to the descender of the "p").

So I wonder if we should add either a "type" or "cause" or both.

    <app>
        <lem>dispositionem</lem>
	<rdg wit="#B" type="error" cause="misspelling">disproositionem</rdg>
    </app>

This would allow us or a user to filter variants. The user could say, I want to filter out all variants that are simply the result of a scribal error, rather than a genuine variant in the manuscript tradition.

**Comment by stenskjaer** [comment]
The possibility of filtering substantial and unsubstantial variants is a good idea. 
I have been thinkin a bit about this now, and I cannot figure out whether this is actually just a reading type. 
By simply adding the reading type `misspelling` it is up to the processor or representation to choose whether such types, there might also be other similar, for example `iteration` which you might term unsubstantial. So maybe this would suffice?
```xml
<app>
    <lem>dispositionem</lem>
    <rdg wit="#B" type="misspelling">disproositionem</rdg>
</app>
```

**Comment by jeffreycwitt** [comment]
We adopted a rdg type called `variation-orthography` in the guidelines for these kinds of variations.
