### ISSUE TITLE
Supporting rdgGrp element within app element

### ISSUE THREAD

**Issue by jeffreycwitt** [lombardpress/lombardpress-schema#38]
I haven't given a lot of thought to this. But I think we need to be able to support the `<rdgGrp>` element as described by the TEI guidelines: http://www.tei-c.org/release/doc/tei-p5-doc/en/html/TC.html#TCAPSU

I think we'll need keep this in mind as we detail a list of app types.

**Comment by nivaca** [comment]
I thought we weren't interested in encoding spelling variations (e.g. 
"imago" v. "ymago") which is one of the motivations of this element.

**Comment by jeffreycwitt** [comment]
I don't think we find a real need for this.
