### ISSUE TITLE
best way to link to TEI doc to IIIF canvas

### ISSUE THREAD

**Issue by jeffreycwitt** [lombardpress/lombardpress-schema#39]
We need to build a recommendation for the best way to link to TEI doc to IIIF canvas

**Comment by stenskjaer** [comment]
Isn't this solved by https://github.com/lombardpress/lombardpress-schema/commit/2043cd6f06c69dd77bd8ed4b37f7afb3cd84043b?

Should it also be copied into the diplomatic guide?

**Comment by jeffreycwitt** [comment]
Yep, closing now.
