### ISSUE TITLE
encodingDesc in diplomatic schema

### ISSUE THREAD

**Issue by stenskjaer** [lombardpress/lombardpress-schema#43]
Is seems to me that the same rules don't apply for the encodingDesc in the diplomatic and critical schemas.

See the rules here: https://github.com/lombardpress/lombardpress-schema/blob/develop/docs/1.0/diplomatic/index.md#rules-6
In a diplomatic transcription you would not necessarily (I would say, should not) have any `app` entries, since that belongs to the critical edition. 
I therefore suggest that rules 2 and 3 be changed. They are now.

> 2. `encodingDesc` **MUST** contain `variantEncoding`.
> 3. `variantEncoding` **MUST** contain `@method` which confirms that the method of variant encoding is parallel-segmentation.

I suggest that the **MUST** is changed to a **MAY** in item 2 and that item 3 is rephrased to make it conditioned by the inclusion of item 2. 

The reason for having a `encodingDesc` in the diplomatic schema, as I see it, is to declare the `schemaRef`. 

I would happily implement the change if you agree.

**Comment by jeffreycwitt** [comment]
Yes, I completely agree. I think that is a hold over from copying the guidelines from the critical to diplomatic. 

In fact, I think we should be even strong and say **SHOULD NOT** or **MAY NOT** contain a `variantEncoding`

Generally, I don't think app element should be allowed in the diplomatic transcription. 

Go ahead an implement the change.
