### ISSUE TITLE
Front element on diplomatic schema

### ISSUE THREAD

**Issue by stenskjaer** [lombardpress/lombardpress-schema#44]
The critical schema includes a recommendation of using the `front` element to indicate the starting point of the text in the different witnesses.
See https://github.com/lombardpress/lombardpress-schema/blob/develop/docs/1.0/critical/index.md#front

Shouldn't that also be included in the diplomatic?

**Comment by jeffreycwitt** [comment]
yes. I also think startsOn should be changed to "starts-on" to follow our general style of preferring dashes to camelCase.
