### ISSUE TITLE
Encoding unsolvable textual problems

### ISSUE THREAD

**Issue by stenskjaer** [lombardpress/lombardpress-schema#5]
It is unclear to me how unsolvable textual problems should be indicated according to the current TEI P5 guidelines. 

An example: “subsidiis magnis †epicuri† constabilitas” (from West, _Textual Criticism_, p. 81). 
As I don't find any tag for indicating such an editorial despair, I suggest one of two possibilities:
- Use `<span type="crux">`
- Create new tag, for instance `<crux>` or something similar. 

The first solution is simpler and in accordance with the suggestion in http://xml.coverpages.org/sperb-mla94.html (search for “crux”). The other suggestion requires additions to the schema, but is more semantically transparent, I think.

Any other ideas?

**Comment by jeffreycwitt** [comment]
Why don't we just use: `<unclear>` and then use available attributes to indicate why it is unclear?

Processors can then represent the different reasons for the `unclear` designation based on the associated enumerated values.

Can you add an example of where `<unclear>` would not solve this. :)

**Comment by nivaca** [comment]
Perhaps the <unclear> tag is meant for subjective (viz. “it’s unclear to me”) rather than objective (viz. “the text is simply unreadable”) textual corruptions?

 

Anyway, the difference is subtle indeed.

 

Best,

 

Nick

**Comment by stenskjaer** [comment]
Well, I think `<unclear>` solves another problem. According to the TEI guidelines:
> `<unclear>` contains a word, phrase, or passage which cannot be transcribed with certainty because it is illegible or inaudible in the source.

So as I read that, `<unclear>` is not a tag indicating a critical, editorial, judgement, it is diplomatic, indicating an objective fact about a particular witness to a text. Some editors are much more inclined to put *cruces* in a text than others. What I am therefore looking for is some way for me as editor to indicate “Here the text makes no sense to me, and I see no good way of solving it.”

In some ways this also involves another question I want to take up, namely the relation between this schema and the TEI guidelines.

**Comment by jeffreycwitt** [comment]
Your explanation makes good sense. But I have not found any other obvious TEI element for this. 

Nevertheless, I don't think it is false to identify a word as "unclear" when it doesn't make sense. It may not be smudged or have any visible defect, but it may still be a very difficult abbreviation, and thus it is still unclear. It's just the reason for it being unclear is different.

Thus I think it is still unclear and then we could differentiate between different types of `<unclear>` values using the `@reason` attribute.

So we could say `<unclear reason="smudged">` or when the abbreviation is ambiguous we could say `<unclear reason="ambiguous">`

We can also indicate our level of certainty about the unclear value using the `@cert="high,medium,low` attribute.

We might think about creating a list of availalibe `@reason` values: 

* smudged == if the word/abbreviation is smudged
* ambiguous == if the abbreviation is ambiguous
* sense == if the word seems clearly written, but doesn't make any sense

We could further categorize these if we wanted to start using the `@type` and `@subtype` attributes.

**Comment by stenskjaer** [comment]
Sure, it's a good point that something can be perfectly visible but still illegible/uncelar, if for instance the abbreviation is strange. There I also agree completely that the `<unclear>` tag is the right one.

But I still wonder whether `<unclear>` should be restricted to a purely diplomatic tag, or might also be used as a critical tag as you suggest with `@reason="sense"`. I get the idea, but feel a bit reluctant because I feel it is a conflation of two different spheres. The one is related to the transcription of one particular witness to a text, the other to the transmission of the text (in a more abstract sense).

But I see that the semantics of the tag `<unclear reason="sense">` is very expressive. When you see that in the encoded text, you might no be in doubt of the meaning of what it means.

Although I am also reluctant to overusing the `@type` attribute, it might also come in handy for making the expression more explicit, e.g.
```
here the <unclear type="textual" reason="sense">gobliwok</unclear> is off.
```
I we wanted to use the `@type`, one might want to distinguish simply between 
- diplomatic, and
- critical
I don't know. 

But then again, as I sit here and wonder what to call an extra tag, if we wanted to distinguish these levels of *aporiai* by tags rather than attributes. And unless you want to create a siglum-inspired tag like `<crux>` or `<obelus>` (which I would be against), I actually think that `<corrupt>` or `<corruption>` might cover the semantics I'm looking for. It is not saying that the meaning is unclear, but worse than that, that the text obviously is corrupt (according to the judgement of the editor). So for instance, it would indicate the problem with the following sentence (based on this paragraph):
```
But then again, as I sit here and wonder what to call an extra tag, if 
we wanted to distinguish these <corrupt>text obviously is corrupt</corrupt>
```

Just a side note: Of course, the use of the certainty attribute is obvious, and should definitely be available.

**Comment by sjhuskey** [comment]
What about using `<orig>` with `@ana="crux"`? That seems semantically honest to me. According to the TEI guidelines, `<orig>` "contains a reading which is marked as following the original, rather than being normalized or corrected." A crux is following the original, and it hasn't been normalized or corrected since, by definition, it can't be. Using `@ana` or `@type` would distinguish it from other uses of `<orig>`.

**Comment by stenskjaer** [comment]
I think that's a very good point about `<orig>`. That might be a solution.

Since `@ana` takes one or more pointers, we could use that with a corresponding definition somewhere else `<orig ana="#crux">`. If we don't like the requirement of defining a reference, `@type` could be used in stead. Since we really don't want or need to give much further explanation at a general level (as the reference of the pointer "#crux" would have to hold for each, you cannot address problems of each instance in the reference), using `@type` seems more suited for the purpose to me.

Any thoughts?

**Comment by sjhuskey** [comment]
I agree with your point about `@ana`. I would support using `@type` instead.

**Comment by sjhuskey** [comment]
Hugh Cayless has just reminded me that `orig` cannot take `@type`, and he raised concerns about `orig`, too. Here are his remarks:

> I think <sic rend="crux"> would be better, wouldn't it? While it may well follow an original, what's printed in a crux might still have been subject to *some* editorial intervention. It'll have to be @rend rather than @type in any case, because neither takes @type. The thing with <orig> is it's paired with <reg>, which tells me it's more for un-normalized text than for incomprehensible text. <sic> on the other hand is paired with <corr>—if you were able to understand what went wrong to produce the crux, you'd correct it. <unclear> is really for illegible text, so it's definitely out.

I trust Hugh's instincts. I think `sic` is a good option.

**Comment by stenskjaer** [comment]
Yeah, his point about `<sic>` as a parallel with `<corr>` is very good. I like that.
But I am a bit worried about the use of `@rend` as I think it gives a wrong impression: That the phenomenon of a textually unsolvable problem has been represented by a crux or dagger symbol in some traditional editions, is arbitrary. So linking the phenomenon with the tag indicating a rendition, goes (to my mind) counter to the idea of separating presentation and content. 

So not having `@type` available is really a shame. The problem is that there isn't really any good suggestions aside from `@ana` and `@rend`, which, in my view, have each of their problems. But in that case | would definitely tend to prefer `@ana`.

I might be on the wrong track here, so what do you guys think?

**Comment by jeffreycwitt** [comment]
@stenskjaer This is a great discussion, but I'm not sure if there is a clear proposal for action here.

Is the proposal that <sic> should be used for unclear situations? Is this perhaps something that can be discerned from the tei guidelines and left out of our documentation? Do our guidelines on "conjecture" cover this?

In the interest of closing issues and finalizing the existing documentation, can we close this issue and see if the problem comes up again? 

If you agree, please go ahead and close the issue. We can always re-open.
