### ISSUE TITLE
variant-iteration

### ISSUE THREAD

**Issue by stenskjaer** [lombardpress/lombardpress-schema#51]
Refresh my memory, where did we land on the question of iterated variants. If we even got around to discussing it.
Take this example:
![skaermbillede 2016-08-04 kl 15 20 22](https://cloud.githubusercontent.com/assets/4047523/17403270/49029c4c-5a57-11e6-9305-a90d2dbc7a5a.png)

The diplomatic transcription reads:
``` xml
anima nec est est <choice><sic>fas()ma</sic><corr>fantasma</corr></choice>
<lb ed="#M"/> nec cum fantasmate quoniam est substancia simplex
```

How would you encode that critically?
I would be inclined to consider it a separate variant type in this way:
``` xml
Sed anima nec
<app>
  <lem>est</lem>
  <rdg wit="#M" type="variant-iteration">est est</rdg>
</app>
```
But since this type represents this particular situation, it could simply yield something like
> 10 est ] *iter.* M

But I can't get that with our current reading types. If I use a current reading type, I suppose I could do like this:
``` xml
Sed anima nec
<app>
  <lem>est</lem>
  <rdg wit="#M" type="variant-substance">est est</rdg>
</app>
```
But that would yield something like:
> 10 est ] est est M

Maybe this second one is more explicit, but I find the first to represent a typical and idiomatic use in traditional apparatuses.

**Comment by jeffreycwitt** [comment]
In our schema guidelines, I believe we suggested: 

```xml
est
<app>
  <lem/>
  <rdg wit="#M" type="variant-present" cause="repetition">est</rdg>
</app>
```
Are there any problems with this?

Also, in the diplomatic transcription, I would have put a `<sic>` around the second "est" so that I knew this wasn't a typo or mistake on my part as an editor.

**Comment by stenskjaer** [comment]
Ahh yes, repetition. I forgot that. That is good.
It is even documented, I just didn't remember it!
