### ISSUE TITLE
Conjecture supplied question

### ISSUE THREAD

**Issue by nivaca** [lombardpress/lombardpress-schema#56]
In my text, all witnesses have: 

> consequens falsum, quia

However, I wish the edition to read:

> consequens falsum <est>, quia

Should I use `conjecture-supplied` for this?

``` xml
Consequens falsum     
            <app>
              <lem type="conjecture-supplied" resp="#NV">est</lem>
              <rdg type="variation-absent" wit="#M #V #T #S" />
            </app>
            , quia
```

**Comment by stenskjaer** [comment]
I think so yes. 
I think the use of `@type="variation-absent"` on the empty readings is facultative, but recommended. So to me your current suggestions looks right.

**Comment by jeffreycwitt** [comment]
I think you can do this two ways. If you don't feel it necessary for there actually to be an apparatus entry here, you can simply write: 

     consequens falsum <supplied>est</supplied>, quia

In this example, when `@resp` is unstated, it is assumed that the main editor is responsible. Likewise, when `<supplied>` is stated with no apparatus entry it is assumed that no other witness support this reading. 

If you want to make an apparatus entry, then I think we would do it just as you have it.

@stenskjaer any disagreements, corrections?

**Comment by stenskjaer** [comment]
Ha! I made my comment at the very same moment. 

But I agree with the idea that just writing `<supplied>est</supplied>` would also do the trick, but then without the apparatus entry. So I guess it comes down to whether you want that.

**Comment by nivaca** [comment]
OK, thanks!
