### ISSUE TITLE
Use of the @type tag for indication scribal corrections and omissions

### ISSUE THREAD

**Issue by stenskjaer** [lombardpress/lombardpress-schema#6]
Pro et contra the use of the `@type` attribute. 
It is documentet in the current draft for 1.0.0 here: https://github.com/lombardpress/lombardpress-schema/blob/master/docs/1.0/critical/index.md#rdg

Is it possible to express the same without the attribute, simply by using the appropriate tags?
I'm just thinking out loud here, and the following would be some suggestions for how to do that. I'm eager to hear your corrections and thoughts.

### Omission:
Critical:
```
ibi
<app>
    <lem>vocem</lem>
    <rdg wit="#T" />
</app>
omisi
```
This does not apply to a diplomatic, since here the text simply doesn't have the expression.

### Correction, addition:
Diplomatic (cf. the discussion in #4):
```
Here I <seg xml:id="segid1">correct<add>ed</add></seg> the word.
```

Critical:
```
Here I
<app>
    <lem>corrected</lem>
    <rdg wit="#T">
        <subst>
            <add>corrected</add>
            <del>correct</del>
        </subst>
    </rdg>
</app>
the word.
```

### Correction, deletion
Diplomatic:
```
<seg xml:id="segid1">corrected<del>ed</del></seg> the word
```
Critical:
```
<app>
    <lem>corrected</lem>
    <rdg wit="#T">
        <subst>
            <add>corrected</add>
            <del>correcteded</del>
        </subst>
    </rdg>
</app>
```

### Correction, replacement:
Diplomatic:
```
<subst>
    <add>improved</add>
    <del>corrected</del>
</subst>
the word
```

Critical:
```
<app>
    <lem>improved</lem>
    <rdg wit="#T">
        <subst>
            <add>improved</add>
            <del>corrected</del>
        </subst>
    </rdg>
</app>
the word
```

## Evaluation:
The critical edition is less detailed in the description of the change. This is clear in both the case of correction by both addition and deletion. I'm not sure that isn't also in line the the more abstract character of a critical edition compared to a diplomatic. At least it is in line with some of what we are currently discussing in #4.

If you find the granularity of the type necessary, I suppose the use of diplomatic editions would do the job. If one wanted to make a critical edition, I suppose this could then be built on top of the diplomatic with references with the `@corresp` attribute. 

Does this increased simplicity also increase the risk of ambiguity?

**Comment by jeffreycwitt** [comment]
I think, we're quite in agreement here. We more or less adopted the above description, but we also added `rdg@types` to each `rdg`
