### ISSUE TITLE
On duplicating info in refs and cits

### ISSUE THREAD

**Issue by nivaca** [lombardpress/lombardpress-schema#65]
Consider the following fragment:

```xml
imago, sicut dicit 
<ref>
  <name ref="#Augustine">
    Augustinus
  </name>, 
  <title ref="#deDiversisQuaestionibus">
    De 83 quaestionibus
  </title>, 
  questione 74,</ref> 
sicut ibi exemplificat: 
<cit>
  <quote>
    <seg type="qs">ut in speculo</seg> 
    inquit, 
    <seg type="qs">est imago hominis quia de illo expressa est.</seg>
    Similiter 
    <seg type="qs">de parentibus et filiis nam et de parente expressa 
      est similitudo filii ut recte dicatur imago.
    </seg>
  </quote>
  <bibl>
    <name ref="#Augustine">Augustinus</name>, 
    <title ref="#deDiversisQuaestionibus">
      De 83 quaestionibus
    </title>,
    q. 74 (PL 40:86): 
    “ut in speculo est imago hominis, quia de illo expressa est; <supplied>. . .</supplied> ut in parentibus et filiis inveniretur imago et aequalitas et similitudo, si intervallum temporis defuisset; nam et de parente expressa est similitudo filii, ut recte dicatur imago.”</bibl>
</cit> 
```

Notice how the `<ref>` and the `<cit>` duplicate info in the `<name>` and `<title>` tags. Is this the right way of encoding the information? (I noticed that we usually haven't done this, and that only in the `<cit>` the full info is included. I think this is not correct, however. What do you think?)

**Comment by jeffreycwitt** [comment]
Yes, I think this is correct. 

The name and title in the `<ref>` represent the original author own citation.
The name and title in the `<bibl>` represent the modern editor's own citation attribution.  

These two concepts need to be kept distinct, and yet in both cases, names and titles are mentioned. Accordingly, in each distinct case, each name and title needs to be semantically marked as such.
