### ISSUE TITLE
Relation between the lombardpress-schema and TEI

### ISSUE THREAD

**Issue by stenskjaer** [lombardpress/lombardpress-schema#7]
We have already several times run into some sort of conflict between our interpretation of the tags supplied by the TEI P5 schema and the TEI P5 guidelines. See for instance #4, and also, I think, #5. The solutions to some of these problems might be more evident, depending on which approach we select in this matter.

I therefore wonder how we want this schema to be related to the TEI P5 guidelines.
I imagine some possibilities. There might be others.

1. Subset of the schema but not guidelines of TEI P5. With a requirement that a validation of a valid Lombard Press encoded file with the TEI P5 schema would also be valid. This would also mean that a processing of the text (to either HTML, LaTeX or whatever) as if it had been TEI P5 would yield a meaningful results, although with a lack of features. The guidelines would then, as is implied, be suggestions for starting the interpretation of the tags and structure of the schema.
2. A "fork" inspired by the TEI P5 schema, but with no requirement of compatability. This would open up for much freer interpretations of the existing tags and creation of new ones. We could here take the existing TEI P5 as inspiration, but would never have to look back.

Without having much insight into the advantages and disadvantages of this, I would be inclined to option 1. Not so much because I think TEI P5 does everything right (otherwise, why make a Lombard Press schema!), but rather because some of the conventions are generally accepted, so many would probably bark at using an identical tag in a completely different way from the TEI idiom. I don't know of which problems this subset solution might provide, aside of course from the fact that some tags already have been defined. 

It would also mean that in many contexts, we would already some some pretty thought through possibilites to choose from. Maybe none of them suit us, and then we could go another way, but they would still be available. Afterall, the guidelines are the product of a very public discussion by a pretty large community of how we best encode this texts. And in this way, we should strive to avoid re-inventing wheels or creating a data silo with the standard.

Edit: Added the last sentence on wheels and silos.

**Comment by jeffreycwitt** [comment]
I think we aim to be a "subset"
