### ISSUE TITLE
Transcription help needed

### ISSUE THREAD

**Issue by mackeyd1** [lombardpress/lombardpress-schema#70]
<img width="891" alt="screen shot 2016-10-07 at 2 30 43 pm" src="https://cloud.githubusercontent.com/assets/22667954/19606619/92c624bc-9791-11e6-81dc-1b8316f4ffab.png">

I'm having a hard time transcribing the second to last word in the second line, which looks like "Ants" to me.

**Comment by stenskjaer** [comment]
Could you maybe give your suggestion for a transcription of the rest of the text? That might help a bit figuring it out.

**Comment by mackeyd1** [comment]
After speaking with Jeff, he informed me that the abbreviation "ants" likely means "antecedentes," which makes sense given the context. My suggested transcription, then, is as follows:

Si ille loquitur horum et angelorum specie differt, ut est communior opinio argumentem nihil valet, quia antecedentes est verum de iisdem contrare, nisi specie.

**Comment by jeffreycwitt** [comment]
Just a quick correction. I think it should be "antecedens" (singular)

**Comment by mackeyd1** [comment]
Ah...of course! Thank you!
