### ISSUE TITLE
Help expanding the common abbreviation "pt" in Ms. Codex 855

### ISSUE THREAD

**Issue by mackeyd1** [lombardpress/lombardpress-schema#72]
<img width="610" alt="screen shot 2016-11-04 at 3 31 41 pm" src="https://cloud.githubusercontent.com/assets/22667954/20019717/fb168300-a2a3-11e6-8f38-bd914c08b6c0.png">

In the above screenshot there is an abbreviation which I am coming across quite frequently but which I am not sure how to expand. The abbreviation "pt" is the 7th word from the left in line 2, and, according to Capelli, could either stand for "post" or "patet." In the sentence in question, the verb "patet" itself appears fully expanded as the first word in line 2. Throughout the rest of the text, however, both the preposition "post" and the verb "patet" appear fully expanded rather infrequently. Here "patet" seems to make the most sense, but my question is whether it can ever be safe to assume that the abbreviation "pt" always stands for one or the other? 

Here is my transcription of the line in question:

3. quod sit per se subsistens patet inde quia anima rationalis nisi "pt" accipere existentiam ab aliquo materiali cum iam probatum sit ipsam esse spiritualem, ergo existentia animae et a nulla causa materiali dependet, ergo est per se subsistens. 

I should also mention that the abbreviation "pt" tends to occur after the abbreviation for nisi in probably 90% of cases. Does this help narrow it down?

**Comment by jeffreycwitt** [comment]
I think this is "potest". 

Double check your previous cases. It will normally be followed by an "infinitive", as it is in this case "potest accipere"

**Comment by mackeyd1** [comment]
Ah, of course! Thanks Jeff.  I knew that that many "post" and "patet" occurrences seemed odd. I'll go back and check them this coming week. 

As far as creating the critical transcription for Disputation 1, should I remove all elements, including names and quotes, or just punctuation elements? 

Best,

Dan

**Comment by jeffreycwitt** [comment]
No don't remove elements for names, titles, quotes, or refs. These should all remain.
