### ISSUE TITLE
Inversion + Substance / Inverstion  

### ISSUE THREAD

**Issue by nivaca** [lombardpress/lombardpress-schema#74]
#S has: "cessaret ista qualitas"
#M has: "cessaret qualitatis ista"

Is this correct?

```XML
<app>
  <lem>cessaret ista qualitas</lem>  
  <rdg wit="#M" type="variation-inversion">ista qualitatis cessaret</rdg>
</app>
```

------------------------

Also this one:

#S has: "igitur visio"
#M has: "visio eius igitur"

```XML
<app>
  <lem>igitur visio</lem>  
  <rdg wit="#M" type="variation-inversion">visio eius igitur</rdg>
</app>
```

**Comment by stenskjaer** [comment]
The first is a substance change as the words are not merely inverted. The second is most simply represented with the substance type, I think. I played with the thought of a nested encoding, but I don't know if it would work right. The thing is, to me, that in both of these situations the difference includes some material being inverted, but it is not only inversions, and should therefore rather be described as substance variants.
Imagine a processor simply renders the variation-inversion like so:
> igitur visio ] *inv. M* 

The actual reading of the witness would be completely opaque. While if you just use the substance variant then it would be clear like this:
> igitur visio ] visio eius igitur *M*

**Comment by nivaca** [comment]
Great. Thanks, Michael.
