### ISSUE TITLE
correction inside a reading

### ISSUE THREAD

**Issue by jeffreycwitt** [lombardpress/lombardpress-schema#82]
I'm review Nicks pull request now and i'm noticing that he has several instances of the following:

```xml
<app>
  <lem>secum compateretur illud</lem>
  <rdg type="variation-substance" wit="#V"> non 
     <app>
        <lem>illud</lem>
        <rdg>
          <subst>
            <del>idem</del>
            <add>illud</add>
          </subst>
        </rdg>
     </app>
   </rdg>
</app>
```

Basically he wants the lemma to be 
"secum compateretur illud"
and the reading to be
"non illud"

but it also wants to indicate that V changed "idem" to "illud"

At present I don't think we can allow apps inside `<rdg>` elements, though we can allow them inside `<lem>` elements.

I think this would either need to be split up into to or we should just ad a witDetail that provides further detail. So I think I would do the following

```xml
<app>
    <lem>secum compateretur illud</lem>
    <rdg type="variation-substance" wit="#V">non illud</rdg>
    <witDetail wit="#V">illud corr. ex idem</witDetail>
</app>
```

Thoughts.

**Comment by nivaca** [comment]
Oh... I thought we could nest apps like so. But I agree with the proposed solution.

**Comment by jeffreycwitt** [comment]
we can nest apps inside lemmas, but not inside rdgs

**Comment by jeffreycwitt** [comment]
well, I take it back. Strictly speaking we can put an app inside a rdg, but I'm extremely unclear how eledmac or any other processor would deal with it.

**Comment by nivaca** [comment]
OK, so the restriction is not TEI's. I think we can manage something with eledmac.

**Comment by jeffreycwitt** [comment]
ok, let me know what you come up with. :)

**Comment by stenskjaer** [comment]
And apparatus entry inside a `rdg` would result in an `\edtext{}` inside an `\Xfootnote{}` in reledmac, and that cannot be done.

The naive processing of the `app` inside the `rdg` could for instance result in something like this in reledmac:
``` latex
\edtext{secum compateretur illud}
  {\lemma{secum compateretur illud}
   \Afootnote{non 
     \edtext{illud}
       {\lemma{illud}
       \Afootnote{illud corr. ex idem O}}
   }}
```

But that cannot compile since the second `\Afootnote` is inside the first. You can nest readings in the lemma, but not the `\Xfootnote{}`.

So I think this is a challenge that must be solved during processing (if you want to solve it automatically) by noticing the type of the nested reading and create an appropriate note in the apparatus note.
In this case it could be something like this:

> 1 secum compateretur illud ] non illud (illud corr. ex idem) V

That could of course be done, but it might involve some pretty crazy complexity to be able to take all possible nested combinations into account intelligently. It might be simple, but I have a feeling that it's nasty.

**Comment by nivaca** [comment]
OK, you're right...

**Comment by jeffreycwitt** [comment]
I've been thinking about this more. 

I want to propose the idea of two new conceptual categories:

* a variation with correction (described here)
* a correction that varies (described in issue #91)

What Nick's example illustrates is the possibility of a correction on an alternate stem. 
(See the attached image below).

If we imagine the main text being a straight line, a variation represents an alternative path. 

When a correction is made on the "alternative path" it becomes difficult to represent this because, with respect to the main line, there is nothing to correct. The very words in need of correction only occur on the alternate path. 

My idea, therefore, is to allow `rdg@type="variation-substance"` to include `<add>` `<del>` and `<subst>` as children.  (But only for the present case, i.e. a correction on an alternate stem)

This is the "variation with correction" case (to be distinguished from a "correction that varies", see #91)

This would look like the following: 

```xml
<app>
  <lem>secum compateretur illud</lem>
  <rdg type="variation-substance" wit="#V"> 
      non 
      <subst>
          <del>idem</del>
          <add>illud</add>
        </subst>
  </rdg>
</app>
```

This will only work, if the `rdg` in question represents one witness. 

So, if there is another witness with an identical `rdg` but no correction, then this variation needs to be recorded in a separate reading. 

In this case, a process could be expected, to recognize any `add` `del` or `subst` element within a "varation-substance" and automatically produce the kind of note that would otherwise be manually written in a witDetail. 

It might look like: 

> secum compateretur illud] non illud *nota* illud *corr. ex* idem

As discussed elsewhere, we can also continue to address this issue with the `witDetail`. In this case, one would simply ignore the correction in the `rdg` and then add a note in `witDetail`. However, since this case is quite common, it is nice to be able to simply add the correction within the `rdg` and not worry about adding an extra `witDetail`.


![img_20170217_111610](https://cloud.githubusercontent.com/assets/1146685/23073178/a726f796-f502-11e6-9d4e-e055bc1ceea1.jpg)
