### ISSUE TITLE
Unreadable gaps

### ISSUE THREAD

**Issue by nivaca** [lombardpress/lombardpress-schema#9]
Consider this image:

![2016-04-23 10 36 29 am](https://cloud.githubusercontent.com/assets/2309005/14762415/46f34ac8-093f-11e6-98be-4594c93a5694.png)

I would usually encode this fragment thus:

`ex hoc quod <gap quantity="1" unit="chars"/>`

Is this right?

**Comment by stenskjaer** [comment]
I interpret `<gap>` to indicate an element that is skipped as an editorial choice. So if that is what you want to convey, I think it could be right. You could add the `@reason` attribute with an appropriate description (smudge or rasura?).

I would probably myself prefer `<unclear>` here, if I had a guess about what to read. Maybe *est* here? `<unclear>` can also have the attributes `@quantity` and `@unit`.

**Comment by jeffreycwitt** [comment]
There is another element called `<space>` that I think is designed for this purpose. 

The TEI guideline say: 

>This element should be used wherever it is desired to record an unusual space in the source text, e.g. space left for a word to be filled in later, for later rubrication, etc. It is not intended to be used to mark normal inter-word space or the like.

See (http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-space.html)[http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-space.html]

Admittedly, the guidelines are not particularly clear about the difference between `<space>` and `<gap>`. (http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-gap.html)[http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-gap.html]. But I think Michael is correct that `<gap>` is designed more for the critical edition that the diplomatic transcription. I think `<gap>` should be used in those cases where the presentation (printed) version of the text would read "[...]", where "[...]" would indicate to the reader there is stuff here but it is so garbled that we don't have any idea what it says. 

So in the case of your example, if there really is a blank space, I would do 

    <space quantity="1" unit="chars"/>

If there actually is something written there, but it is just very hard to read, I would use `<unclear>` and then in the critical text either use `<unclear`> again or `<gap>`.

If people approve of adopting `<space quantity="1" unit="chars"/>`, let me know and I will add this to the 1.0.0 specification and close this issue. :)

**Comment by nivaca** [comment]
I didn’t know about these attributes of <unclear>. That’s a good suggestion, then.

**Comment by stenskjaer** [comment]
@jeffreycwitt I had the feeling this sort of element would exist, but I couldn't find it when I was thinking of an answer. 
I highly approve of adding it, since it will be perfect for that case where for instance it looks like the scribe has skipped a word or the like. 
Great!

**Comment by jeffreycwitt** [comment]
Here's a good example of a `<space>`: 

![image](https://cloud.githubusercontent.com/assets/1146685/15153156/295040b0-16a6-11e6-917a-98270550a38b.png)

I'm currently encoding it as follows: 

    sunt <pc ana="#virgula"/> <space unit="chars" quantity="8" /> emenda

The quantity is approximate (I counted the characters in the line below it to get the approximate quantity of the space).

But I also know from another manuscript that this missing word is "voluntaria". Is there away to to include this in the `<space>` element?

**Comment by nivaca** [comment]
If this is a diplomatic transcription, there is no need of including “voluntaria”, is it?

Cheers.

**Comment by jeffreycwitt** [comment]
You're correct. 

Identifying the <space> is the correct mark for the diplomatic transcription. 

But someday it might nice to have the option let a user hover over the gap, and then for the correct word (if we know it) to be visible. 

I think something like the traditional `<choice><sic><space/></sic><corr>voluntaria</corr></choice>` would provide this kind of optional capability. 

Now that I think about it, this solution seems obvious. 

If you guys like this, I will add this to the 1.0.0 spec and close this issue.

**Comment by nivaca** [comment]
I agree. Cheers.

**Comment by stenskjaer** [comment]
Me too. Sounds good.

**Comment by stenskjaer** [comment]
An extra note on this. I take the `<space>` to also be useful in the case of erasures in the text that are completely unreadable.

For example this:
![skaermbillede 2016-05-13 kl 11 34 30](https://cloud.githubusercontent.com/assets/4047523/15243923/cadedf54-18fe-11e6-97ce-e5083ad10d0b.png)
I transcribe that as
```
in actu <space reason="rasura" quantity="1" unit="chars" /> intellectiva

**Comment by stenskjaer** [comment]
Another note, this time on the `<choice>` option.

Let me take Jeff's example: 
```
<choice><sic><space/></sic><corr>voluntaria</corr></choice>
```
Wouldn't that be more accurately represented with the `<supplied>` tag? Like so:

```
<choice><sic><space/></sic><supplied>voluntaria</supplied></choice>
```
Because that represents content that is not present in the text, but that the editor is pretty certain should be there. So this is not a correction of something obviously wrong, but the addition of something obviously missing.
